### ISSUE TITLE
可以做到每5分钟生成一个日志文件吗

### ISSUE THREAD

**Issue by lvgithub** [hezedu/log-master#1]

**Comment by hezedu** [comment]
可以呀,5秒钟都可以

**Comment by hezedu** [comment]
兄弟，由于你的issues，我又更新了下本项目。现在切割正在被写入的log文件，**可保持完整性。**

API不变。只是不再支持window了。

`npm install log-master@1 --save` 快更新一下吧。

**Comment by lvgithub** [comment]
谢了 兄弟

**Comment by lvgithub** [comment]
我的日志的文件没有记录时间可以切割吗

**Comment by hezedu** [comment]
不客气，你是说跟日志内容里没有记录时间？没关系。它根本不会读取日志内容。

 只要配置好后会定期以时间单位生成文件夹的。
